# Deriving the latest base image
FROM python:3.7
LABEL Maintainer="eugenegitonga"
# Defines the working directory of a Docker container
WORKDIR /app
# copies files from a local source location to a destination in the Docker container.
COPY mars_rover_solution.py ./app

CMD [ "python", "./mars_rover_solution.py"]





